#!/usr/bin/env bash
# install.sh — wire the music skill into Claude Code.
#
# Three operations:
#   1. UserPromptSubmit hook → vibe-hook.sh appended to ~/.claude/settings.json
#   2. Statusline option     → ~/.claude/statuslines/music.sh wrapper installed
#   3. Discovery pointer     → ~/.claude/CLAUDE.md gets the play-history line
#
# Idempotent: rerunning is safe.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$REPO_DIR/bin"
SETTINGS="$HOME/.claude/settings.json"
STATUSLINES_DIR="$HOME/.claude/statuslines"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
HISTORY_DIR="$HOME/.cache/vibe"
SUPPORT_DIR="$HOME/Library/Application Support/vibe"
PLIST="$HOME/Library/LaunchAgents/supply.vibe.poll.plist"
PLIST_LABEL="supply.vibe.poll"

HOOK_CMD="bash \"$BIN_DIR/vibe-hook.sh\""
HOOK_MARK="$BIN_DIR/vibe-hook.sh"
CLAUDE_MD_LINE='- Music play history at `~/.cache/vibe/play_history.md` (managed by music skill); read when user asks about listening patterns or vibe drift.'

say() { printf '\033[36m[music]\033[0m %s\n' "$*"; }
fail() { printf '\033[31m[music]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. dependency check ─────────────────────────────────────────────
say "checking dependencies"
for bin in nowplaying-cli jq curl python3; do
  command -v "$bin" >/dev/null 2>&1 || fail "missing dependency: $bin (try: brew install $bin)"
done

# ── 2. ensure dirs ──────────────────────────────────────────────────
mkdir -p "$STATUSLINES_DIR" "$HISTORY_DIR" "$(dirname "$SETTINGS")" "$SUPPORT_DIR" "$(dirname "$PLIST")"

# ── 3. patch settings.json (append hook, don't clobber) ─────────────
say "registering UserPromptSubmit hook"
[[ -f "$SETTINGS" ]] || echo '{}' > "$SETTINGS"

# Skip if our hook is already present.
if jq -e --arg m "$HOOK_MARK" '
  [.hooks.UserPromptSubmit // [] | .[].hooks // [] | .[].command // ""]
  | any(. | contains($m))
' "$SETTINGS" >/dev/null 2>&1; then
  say "  hook already registered — skipping"
else
  tmp="$(mktemp)"
  jq --arg cmd "$HOOK_CMD" '
    .hooks //= {} |
    .hooks.UserPromptSubmit //= [] |
    .hooks.UserPromptSubmit += [{
      hooks: [{
        type: "command",
        command: $cmd,
        timeout: 5
      }]
    }]
  ' "$SETTINGS" > "$tmp"
  mv -f "$tmp" "$SETTINGS"
  say "  added"
fi

# ── 4. install statusline vibe option ───────────────────────────────
# music is a composing vibe: it runs the user's existing base vibe
# (default "pomodoro") first, then appends the 🎧 line so context bar /
# weather / etc. stay visible. Override base with VIBE_BASE env var.
say "installing statusline option at $STATUSLINES_DIR/music.sh"
cat > "$STATUSLINES_DIR/music.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by music install.sh
input="\$(cat)"
BASE="\${VIBE_BASE:-pomodoro}"
BASE_SCRIPT="\$HOME/.claude/statuslines/\${BASE}.sh"
if [[ -x "\$BASE_SCRIPT" && "\$BASE" != "music" ]]; then
  printf '%s' "\$input" | bash "\$BASE_SCRIPT" || true
fi
printf '%s' "\$input" | bash "$BIN_DIR/vibe-statusline.sh" || true
EOF
chmod +x "$STATUSLINES_DIR/music.sh"

# ── 5. background polling daemon ────────────────────────────────────
# Claude Code's statusline timer is unreliable in current versions and
# nothing else triggers vibe-poll.sh between user messages. A launchd
# KeepAlive job runs a loop with `sleep 2` so the cache stays fresh and
# the 30s history-append threshold fires regardless of user activity.
# Source files must live outside ~/Documents because launchd-spawned
# processes lack TCC access there.
say "installing background poll daemon"
cp "$BIN_DIR/vibe-poll.sh" "$SUPPORT_DIR/poll.sh"
chmod +x "$SUPPORT_DIR/poll.sh"
cat > "$SUPPORT_DIR/daemon.sh" <<EOF
#!/bin/bash
# Long-running poll loop. macOS throttles short StartInterval values,
# so we use one persistent process kept alive by launchd instead.
# Each poll is hard-bounded so a hung curl or wedged nowplaying-cli
# call can't pin the daemon and stale the cache.
INTERVAL=2
POLL_TIMEOUT=10
POLL="$SUPPORT_DIR/poll.sh"
TIMEOUT_BIN=""
command -v gtimeout >/dev/null 2>&1 && TIMEOUT_BIN="gtimeout"
[[ -z "\$TIMEOUT_BIN" ]] && command -v timeout >/dev/null 2>&1 && TIMEOUT_BIN="timeout"
while true; do
  if [[ -n "\$TIMEOUT_BIN" ]]; then
    "\$TIMEOUT_BIN" "\$POLL_TIMEOUT" /bin/bash "\$POLL" 2>>/tmp/vibe-poll.err
  else
    /bin/bash "\$POLL" 2>>/tmp/vibe-poll.err
  fi
  sleep "\$INTERVAL"
done
EOF
chmod +x "$SUPPORT_DIR/daemon.sh"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$SUPPORT_DIR/daemon.sh</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>StandardErrorPath</key>
    <string>/tmp/vibe-poll.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
EOF

# Reload (unload then load) so changes to plist or scripts take effect.
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
say "  daemon loaded ($PLIST_LABEL)"

# ── 6. CLAUDE.md pointer (idempotent) ───────────────────────────────
say "ensuring play-history pointer in $CLAUDE_MD"
touch "$CLAUDE_MD"
if grep -qF "vibe/play_history.md" "$CLAUDE_MD"; then
  say "  pointer already present — skipping"
else
  printf '\n%s\n' "$CLAUDE_MD_LINE" >> "$CLAUDE_MD"
  say "  appended"
fi

say "done."
cat <<'INSTRUCT'

Next steps:
  1. The hook is now active for any NEW Claude Code session. Existing
     sessions won't see it until you /clear or restart.

  2. The launchd daemon is already running and polling every 2s. Cache
     stays fresh whether or not you're talking to Claude. Verify:
       cat /tmp/vibe-current.json
       launchctl list | grep supply.vibe.poll

  3. To enable the 🎧 statusline as your default vibe, edit
     ~/.claude/statusline-command.sh and change the fallback from
     "pomodoro" to "music". (Per-session vibe files don't reliably
     work because Claude Code's PPID rotates between statusline ticks.)

  4. Verify history append after listening to a song for 30s+:
       tail -n 5 ~/.cache/vibe/play_history.md

  5. Note: Claude Code's statusline doesn't auto-refresh on a timer in
     current versions — it only re-renders on events (new assistant
     message, mode change, etc.). The daemon keeps the cache fresh so
     when statusline DOES render, it shows the latest. The countdown
     therefore won't tick visually between events; that's a Claude Code
     limitation, not an music bug.

INSTRUCT
