#!/usr/bin/env bash
# install.sh — wire the music skill into Claude Code.
#
# Three operations:
#   1. UserPromptSubmit hook → music-hook.sh appended to ~/.claude/settings.json
#   2. Statusline option     → ~/.claude/statuslines/music.sh wrapper installed
#   3. Discovery pointer     → ~/.claude/CLAUDE.md gets the play-history line
#
# Idempotent: rerunning is safe.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$REPO_DIR/bin"
COMMANDS_DIR="$REPO_DIR/commands"
SETTINGS="$HOME/.claude/settings.json"
STATUSLINES_DIR="$HOME/.claude/statuslines"
COMMANDS_USER_DIR="$HOME/.claude/commands"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
HISTORY_DIR="$HOME/.cache/music"
SUPPORT_DIR="$HOME/Library/Application Support/music"
PLIST="$HOME/Library/LaunchAgents/supply.music.poll.plist"
PLIST_LABEL="supply.music.poll"

HOOK_CMD="bash \"$BIN_DIR/music-hook.sh\""
HOOK_MARK="$BIN_DIR/music-hook.sh"
CLAUDE_MD_LINE='- Music play history at `~/.cache/music/play_history.md` (managed by music skill); read when user asks about listening patterns or vibe drift.'

say() { printf '\033[36m[music]\033[0m %s\n' "$*"; }
fail() { printf '\033[31m[music]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. dependency check ─────────────────────────────────────────────
say "checking dependencies"
for bin in nowplaying-cli jq curl python3; do
  command -v "$bin" >/dev/null 2>&1 || fail "missing dependency: $bin (try: brew install $bin)"
done

# ── 2. ensure dirs ──────────────────────────────────────────────────
mkdir -p "$STATUSLINES_DIR" "$HISTORY_DIR" "$(dirname "$SETTINGS")" "$SUPPORT_DIR" "$(dirname "$PLIST")" "$COMMANDS_USER_DIR"

# ── 3. patch settings.json (append hook, don't clobber) ─────────────
say "registering UserPromptSubmit hook"
[[ -f "$SETTINGS" ]] || echo '{}' > "$SETTINGS"

# Skip if our hook is already present.
if jq -e --arg m "$HOOK_MARK" '
  [.hooks.UserPromptSubmit // [] | .[].hooks // [] | .[].command // ""]
  | any(. | contains($m))
' "$SETTINGS" >/dev/null 2>&1; then
  say "  hook already registered — skipping"
else
  tmp="$(mktemp)"
  jq --arg cmd "$HOOK_CMD" '
    .hooks //= {} |
    .hooks.UserPromptSubmit //= [] |
    .hooks.UserPromptSubmit += [{
      hooks: [{
        type: "command",
        command: $cmd,
        timeout: 5
      }]
    }]
  ' "$SETTINGS" > "$tmp"
  mv -f "$tmp" "$SETTINGS"
  say "  added"
fi

# ── 4. install statusline vibe option ───────────────────────────────
# music is a composing vibe: it runs the user's existing base vibe
# (default "pomodoro") first, then appends the 🎧 line so context bar /
# weather / etc. stay visible. Override base with VIBE_BASE env var.
say "installing statusline option at $STATUSLINES_DIR/music.sh"
cat > "$STATUSLINES_DIR/music.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by music install.sh
input="\$(cat)"
BASE="\${VIBE_BASE:-pomodoro}"
BASE_SCRIPT="\$HOME/.claude/statuslines/\${BASE}.sh"
if [[ -x "\$BASE_SCRIPT" && "\$BASE" != "music" ]]; then
  printf '%s' "\$input" | bash "\$BASE_SCRIPT" || true
fi
printf '%s' "\$input" | bash "$BIN_DIR/music-statusline.sh" || true
EOF
chmod +x "$STATUSLINES_DIR/music.sh"

# ── 5. background polling daemon ────────────────────────────────────
# Claude Code's statusline timer is unreliable in current versions and
# nothing else triggers music-poll.sh between user messages. A launchd
# KeepAlive job runs a loop with `sleep 2` so the cache stays fresh and
# the 30s history-append threshold fires regardless of user activity.
# Source files must live outside ~/Documents because launchd-spawned
# processes lack TCC access there.
say "installing background poll daemon"
cp "$BIN_DIR/music-poll.sh"          "$SUPPORT_DIR/poll.sh"
cp "$BIN_DIR/music-enrich.sh"        "$SUPPORT_DIR/music-enrich.sh"
cp "$BIN_DIR/music-spotify-auth.sh"  "$SUPPORT_DIR/music-spotify-auth.sh"
cp "$BIN_DIR/music-player-state.sh"  "$SUPPORT_DIR/music-player-state.sh"
chmod +x "$SUPPORT_DIR/poll.sh" "$SUPPORT_DIR/music-enrich.sh" "$SUPPORT_DIR/music-player-state.sh"
cat > "$SUPPORT_DIR/daemon.sh" <<EOF
#!/bin/bash
# Long-running poll loop. macOS throttles short StartInterval values,
# so we use one persistent process kept alive by launchd instead.
# Each poll is hard-bounded so a hung curl or wedged nowplaying-cli
# call can't pin the daemon and stale the cache.
#
# Prefers GNU timeout (gtimeout from coreutils, or 'timeout' on Linux);
# falls back to a pure-bash watchdog when neither is on PATH (macOS
# ships without coreutils). The fallback enables job control (set -m)
# so the poll runs in its own process group, then sends SIGKILL to the
# whole group — otherwise hung curl/nowplaying-cli children survive as
# orphans and accumulate over time.
INTERVAL=2
POLL_TIMEOUT=15
POLL="$SUPPORT_DIR/poll.sh"

run_poll() {
  local bin=""
  command -v gtimeout >/dev/null 2>&1 && bin="gtimeout"
  [[ -z "\$bin" ]] && command -v timeout >/dev/null 2>&1 && bin="timeout"
  if [[ -n "\$bin" ]]; then
    # -k 2: if SIGTERM doesn't take in 2s, follow with SIGKILL.
    "\$bin" -k 2 "\$POLL_TIMEOUT" /bin/bash "\$POLL" 2>>/tmp/music-poll.err
    return
  fi
  # Pure-bash fallback. set -m makes each backgrounded command a
  # process group leader; "kill -- -PID" then signals the whole group.
  set -m
  /bin/bash "\$POLL" 2>>/tmp/music-poll.err &
  local pid=\$!
  (
    sleep "\$POLL_TIMEOUT"
    kill -TERM -- "-\$pid" 2>/dev/null
    sleep 1
    kill -KILL -- "-\$pid" 2>/dev/null
  ) &
  local wd=\$!
  wait "\$pid" 2>/dev/null
  kill -KILL "\$wd" 2>/dev/null
  wait "\$wd" 2>/dev/null
  set +m
}

while true; do
  run_poll
  sleep "\$INTERVAL"
done
EOF
chmod +x "$SUPPORT_DIR/daemon.sh"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$SUPPORT_DIR/daemon.sh</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>StandardErrorPath</key>
    <string>/tmp/music-poll.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
EOF

# Reload (unload then load) so changes to plist or scripts take effect.
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
say "  daemon loaded ($PLIST_LABEL)"

# ── 6. slash commands: symlink skills/music/commands/*.md into
#       ~/.claude/commands/ so users can invoke /vibe etc. directly.
#       Symlink (not copy) so repo edits pick up immediately and users
#       can't end up with stale copies after a git pull.
say "installing slash commands into $COMMANDS_USER_DIR"
if [[ -d "$COMMANDS_DIR" ]]; then
  while IFS= read -r -d '' cmd_file; do
    base="$(basename "$cmd_file")"
    target="$COMMANDS_USER_DIR/$base"
    if [[ -L "$target" ]]; then
      # Our symlink (or someone else's) — overwrite ours only.
      existing="$(readlink "$target")"
      if [[ "$existing" == "$cmd_file" ]]; then
        say "  /${base%.md} already linked — skipping"
        continue
      fi
      rm -f "$target"
      ln -s "$cmd_file" "$target"
      say "  /${base%.md} relinked"
    elif [[ -e "$target" ]]; then
      # Real file — user has a same-named command. Don't clobber.
      say "  /${base%.md} exists as a regular file — skipping to avoid clobber"
    else
      ln -s "$cmd_file" "$target"
      say "  /${base%.md} linked"
    fi
  done < <(find "$COMMANDS_DIR" -maxdepth 1 -type f -name '*.md' -print0)
fi

# ── 7. CLAUDE.md pointer (idempotent) ───────────────────────────────
say "ensuring play-history pointer in $CLAUDE_MD"
touch "$CLAUDE_MD"
if grep -qF "music/play_history.md" "$CLAUDE_MD"; then
  say "  pointer already present — skipping"
else
  printf '\n%s\n' "$CLAUDE_MD_LINE" >> "$CLAUDE_MD"
  say "  appended"
fi

say "done."
cat <<'INSTRUCT'

Next steps:
  1. The hook is now active for any NEW Claude Code session. Existing
     sessions won't see it until you /clear or restart.

  2. The launchd daemon is already running and polling every 2s. Cache
     stays fresh whether or not you're talking to Claude. Verify:
       cat /tmp/music-current.json
       launchctl list | grep supply.music.poll

  3. To enable the 🎧 statusline as your default vibe, edit
     ~/.claude/statusline-command.sh and change the fallback from
     "pomodoro" to "music". (Per-session vibe files don't reliably
     work because Claude Code's PPID rotates between statusline ticks.)

  4. Verify history append after listening to a song for 30s+:
       tail -n 5 ~/.cache/music/play_history.md

  5. Note: Claude Code's statusline doesn't auto-refresh on a timer in
     current versions — it only re-renders on events (new assistant
     message, mode change, etc.). The daemon keeps the cache fresh so
     when statusline DOES render, it shows the latest. The countdown
     therefore won't tick visually between events; that's a Claude Code
     limitation, not an music bug.

INSTRUCT
