#!/usr/bin/env bash
# install.sh — wire the attune skill into Claude Code.
#
# Three operations:
#   1. UserPromptSubmit hook → vibe-hook.sh appended to ~/.claude/settings.json
#   2. Statusline option     → ~/.claude/statuslines/attune.sh wrapper installed
#   3. Discovery pointer     → ~/.claude/CLAUDE.md gets the play-history line
#
# Idempotent: rerunning is safe.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$REPO_DIR/bin"
SETTINGS="$HOME/.claude/settings.json"
STATUSLINES_DIR="$HOME/.claude/statuslines"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
HISTORY_DIR="$HOME/.cache/vibe"

HOOK_CMD="bash \"$BIN_DIR/vibe-hook.sh\""
HOOK_MARK="$BIN_DIR/vibe-hook.sh"
CLAUDE_MD_LINE='- Music play history at `~/.cache/vibe/play_history.md` (managed by attune skill); read when user asks about listening patterns or vibe drift.'

say() { printf '\033[36m[attune]\033[0m %s\n' "$*"; }
fail() { printf '\033[31m[attune]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. dependency check ─────────────────────────────────────────────
say "checking dependencies"
for bin in nowplaying-cli jq curl python3; do
  command -v "$bin" >/dev/null 2>&1 || fail "missing dependency: $bin (try: brew install $bin)"
done

# ── 2. ensure dirs ──────────────────────────────────────────────────
mkdir -p "$STATUSLINES_DIR" "$HISTORY_DIR" "$(dirname "$SETTINGS")"

# ── 3. patch settings.json (append hook, don't clobber) ─────────────
say "registering UserPromptSubmit hook"
[[ -f "$SETTINGS" ]] || echo '{}' > "$SETTINGS"

# Skip if our hook is already present.
if jq -e --arg m "$HOOK_MARK" '
  [.hooks.UserPromptSubmit // [] | .[].hooks // [] | .[].command // ""]
  | any(. | contains($m))
' "$SETTINGS" >/dev/null 2>&1; then
  say "  hook already registered — skipping"
else
  tmp="$(mktemp)"
  jq --arg cmd "$HOOK_CMD" '
    .hooks //= {} |
    .hooks.UserPromptSubmit //= [] |
    .hooks.UserPromptSubmit += [{
      hooks: [{
        type: "command",
        command: $cmd,
        timeout: 5
      }]
    }]
  ' "$SETTINGS" > "$tmp"
  mv -f "$tmp" "$SETTINGS"
  say "  added"
fi

# ── 4. install statusline vibe option ───────────────────────────────
say "installing statusline option at $STATUSLINES_DIR/attune.sh"
cat > "$STATUSLINES_DIR/attune.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by attune install.sh
exec "$BIN_DIR/vibe-statusline.sh"
EOF
chmod +x "$STATUSLINES_DIR/attune.sh"

# ── 5. CLAUDE.md pointer (idempotent) ───────────────────────────────
say "ensuring play-history pointer in $CLAUDE_MD"
touch "$CLAUDE_MD"
if grep -qF "vibe/play_history.md" "$CLAUDE_MD"; then
  say "  pointer already present — skipping"
else
  printf '\n%s\n' "$CLAUDE_MD_LINE" >> "$CLAUDE_MD"
  say "  appended"
fi

say "done."
cat <<'INSTRUCT'

Next steps:
  1. Hook is active for any NEW Claude Code session. Existing sessions won't see it.

  2. To enable the 🎧 statusline in your CURRENT session, run:
       echo attune > "/tmp/.claude-session-$PPID/vibe"
     (Run inside the Claude Code terminal session, not from outside.)

     To make it the default for new sessions, edit
     ~/.claude/statusline-command.sh and change the fallback "pomodoro"
     to "attune".

  3. Verify the cache after a song change:
       cat /tmp/vibe-current.json

  4. Verify history append after listening to a song for 30s+:
       tail -n 5 ~/.cache/vibe/play_history.md

INSTRUCT
